spring.application.name=url-shortener

#Redis Connections
spring.data.redis.host=localhost
spring.data.redis.port=6379
spring.data.redis.timeout=2000ms
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0

#Server connections:
server.port=8080

#base configurations
url-shortener.base_url=http://localhost:8080
url-shortener.short-code.length=7
url-shortener.short-code.max-attempts=10
url-shortener.rate-limit.requests-per-minute=2
url-shortener.rate-limit.requests-per-hour=10
url-shortener.cache.ttl-minutes=30
url-shortener.cleanup.interval-minutes=5
url-shortener.cleanup.expired-urls-batch-size=100
